# Generated by Django 4.1.3 on 2022-11-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TagsCategories',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
                ('tags', models.ForeignKey(db_column='tags', on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tags')),
            ],
            options={
                'db_table': 'tags_categories',
            },
        ),
    ]
