version: "3.8"

networks:
  django-backend-net-local:

volumes:
  local_postgresql:
  local_postgresql_backups:
  pgdata:
    driver: local

services:

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    networks:
      - django-backend-net-local

  postgres:
    # build:
    #   context: .
      # dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres:15-alpine
    ports:
      - "5434:5433"
    volumes:
      # - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - local_postgresql:/var/lib/postgresql/data:rw
      - local_postgresql_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - django-backend-net-local