# Generated by Django 4.1.3 on 2022-11-23 04:55

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.blog.models.blog_directory_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.blog.models.blog_directory_path)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='user.userauth')),
                ('category', models.ManyToManyField(to='category.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='user.userauth')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
