# Generated by Django 4.1.3 on 2022-11-23 04:25

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('category', '0002_remove_category_parent_category_description_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.userauth'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.blog_directory_path),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='user.userauth')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
