# Generated by Django 4.1.3 on 2022-12-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsforusers',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
