# Generated by Django 4.1.3 on 2022-12-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionsforusers_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planssubscriptions',
            name='subscription',
        ),
    ]
