# Generated by Django 4.1.3 on 2022-12-18 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_planssubscriptions_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='planssubscriptions',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptions', verbose_name='subscription'),
            preserve_default=False,
        ),
    ]
