# Generated by Django 4.1.3 on 2022-11-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_rename_description_post_content_post_author_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='user.userauth')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
