# Generated by Django 4.1.3 on 2022-11-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(db_column='follower', on_delete=django.db.models.deletion.DO_NOTHING, related_name='follower', to='user.userauth')),
                ('following', models.ForeignKey(db_column='following', on_delete=django.db.models.deletion.DO_NOTHING, related_name='following', to='user.userauth')),
            ],
            options={
                'db_table': 'following',
            },
        ),
    ]
